# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-15 08:24
from __future__ import unicode_literals
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='data_groups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_removable', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'data_groups',
            },
        ),
        migrations.CreateModel(
            name='gis_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=datetime.datetime.now)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('data_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.data_groups')),
            ],
            options={
                'db_table': 'gis_data',
            },
        ),
        migrations.CreateModel(
            name='gis_data_meta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100)),
                ('value', models.TextField()),
                ('data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.gis_data')),
            ],
            options={
                'db_table': 'gis_data_meta',
            },
        ),
        migrations.CreateModel(
            name='options',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_name', models.CharField(max_length=100)),
                ('value', models.TextField()),
                ('is_removable', models.BooleanField(default=False)),
                ('data_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='portal.data_groups')),
            ],
            options={
                'db_table': 'options',
            },
        ),
    ]
